---

- name: 'check status of AWS Config in {{ config_region }}'
  command: >
    aws configservice get-status
                      --region '{{ config_region }}'
                      --profile '{{ profile }}'
  register: config_status
  changed_when: False


- block:

  - name: 'create SNS topic in {{ config_region }}'
    command: >
      aws sns create-topic
              --name aws-config
              --region '{{ config_region }}'
              --profile '{{ profile }}'

  - name: 'subscribe to AWS Config in {{ config_region }}'
    command: >
      aws configservice subscribe
                        --iam-role arn:aws:iam::{{ account }}:role/aws-config
                        --region '{{ config_region }}'
                        --s3-bucket '{{ awslogs_bucket }}'
                        --sns-topic aws-config
                        --profile '{{ profile }}'

  - name: call optional notifier
    include: 'roles/{{ notifier_role }}/tasks/main.yml'
    vars:
      message: >
        enabled <b>AWS Config</b> in
        <a href="{{ config_url }}?region={{ config_region }}">{{
          config_region }} in account {{ profile }}</a>
    when: notifier_role is defined

  when: '"recorder: ON" not in config_status.stdout_lines'
