---

- name: set global facts
  set_fact:
    _aws_config_url: 'https://console.aws.amazon.com/config/home'

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-config</b>
      on <a href="{{ _aws_config_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined

- include_tasks: regions.yml

- include_tasks: activate.yml
  vars:
    config_region: '{{ item }}'
  with_items: '{{ _aws_config_active_regions }}'

- include_tasks: deactivate.yml
  vars:
    config_region: '{{ item }}'
  with_items: '{{ _aws_config_inactive_regions }}'

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-config</b>
      on <a href="{{ _aws_config_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined
