---

- name: list all AWS regions
  aws_region_info:
    profile: '{{ aws_profile }}'
  register: _aws_config_region_facts

- name: set all AWS regions fact
  set_fact:
    _aws_config_all_regions: >-
      {{
        _aws_config_region_facts.regions
        | json_query("[*].region_name")
        | sort
      }}

- name: set configured AWS regions fact
  set_fact:
    _aws_config_configured_regions: >-
      {% if aws_config_regions == 'ALL' -%}
      {{ _aws_config_all_regions }}
      {% elif aws_config_regions == 'NONE' -%}
      {{ [] }}
      {% else -%}
      {{ aws_config_regions }}
      {%- endif -%}

- name: set added and removed AWS regions fact
  set_fact:
    _aws_config_active_regions: >-
      {{ _aws_config_configured_regions }}
    _aws_config_inactive_regions: >-
      {{ _aws_config_all_regions | difference(_aws_config_configured_regions) }}
